### ISSUE TITLE
Requires gimp-python to be installed in GIMP 2.10

### ISSUE THREAD

**Issue by pjohanneson** [themaninthesuitcase/gimp-startrail-compositor#16]
I couldn't install the plugin after upgrading from GIMP 2.8 to 2.10 on Ubuntu 18.04. `startrail.py` was in the correct directory, and it had the `x` bit set.

Eventually I realized I was seeing the following error:

> Failed to execute child process “python” (No such file or directory)

I found [this thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907539) which led me to try installing `gimp-python` (`sudo apt install gimp-python`), which worked.

**Comment by pjohanneson** [comment]
Please feel free to close this, as I've solved the issue I was having. I just wanted to record it in case anyone else is having the same problem.

**Comment by shimonomihs** [comment]
I can't install gimp-python to my machine, do I have to add some repo? Ubuntu 20.04, Gimp 2.10

**Comment by pjohanneson** [comment]
There's some info here -- https://www.gimp-forum.net/Thread-Heal-Selection-Missing-from-Gimp-on-Ubuntu-20-04 -- but **use at your own risk**. (One user says he was able to install 18.10's version of gimp-python and its dependencies, and things worked fine.)
