### ISSUE TITLE
Light Frame Path does not exist

### ISSUE THREAD

**Issue by BalintXHD** [themaninthesuitcase/gimp-startrail-compositor#18]
Now i am a beginner with astrophotography i might have missed something

I... don't have a  light frame path? how do i make one?

Quick edit: if you have your lights taken and youre trying to make star trail photo make sure your lights are in a folder path that hasnt got any á é ű like characters

**Comment by shimonomihs** [comment]
Light frames are the ones you most likely took (photos of stars), you can also take calibration frames (dark, flat, bias) which can improve the final picture by eliminating iso grain and such (this addon only supports dark frames). You can read more for example here https://nightskypix.com/calibration-frames/

**Comment by themaninthesuitcase** [comment]
As @ShimonHoranek says the light frames are just the pictures you took. 

The light frame path is just the path to the folder that contains those photos and is what will be stacked into your final result.

**Comment by BalintXHD** [comment]
so sorry, i have my light frames, i put it in and it tells me that("Light Frame Path does not exist")

**Comment by BalintXHD** [comment]
![kép](https://github.com/themaninthesuitcase/gimp-startrail-compositor/assets/36235183/0630edb4-f151-4ba0-82d0-2bed014a65ef)
![kép](https://github.com/themaninthesuitcase/gimp-startrail-compositor/assets/36235183/5bb17307-3471-46d4-bcc7-3fdfca2dc398)

**Comment by BalintXHD** [comment]
btw do you account for accented characters in file path?

**Comment by BalintXHD** [comment]
SOLVED IT! You haven't accounted for accented characters.
