### ISSUE TITLE
README: mention the need for 'execute' permission

### ISSUE THREAD

**Issue by ratmonkey** [themaninthesuitcase/gimp-startrail-compositor#3]
Can you mention in README that the plugin file needs execute permission? I downloaded the raw file and didn't realize that it requires execute permissions for gimp to load it.

**Comment by themaninthesuitcase** [comment]
I'm sure this used to be somewhere, probably on the old GIMP repository page.  I'll update it.

**Comment by themaninthesuitcase** [comment]
Fixed in 0f315cd
